import { Montserrat } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";

export const metadata = {
  title: "CRUD APPLICATION",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${montserrat.className} antialiased`}
          suppressHydrationWarning
        >
          {children}
        </body>
      </Provider>
    </html>
  );
}
